from parameter_inference.mcmc_base import ParameterMCMCBase, _H

class ParameterMetropolisHasings(ParameterMCMCBase):
    def __init__(self, hypothesis_space: _H) -> None:
        super().__init__(hypothesis_space)
    def propose(self, ): ...
    def acceptance_probs(self, ): ...
    def accept_or_reject(self, ): ...
